version: "3.7"
services:
  notifier:
    container_name: pubsub-gateway
    image: pubsub-gateway
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      MODE: receiver
      CONFIG_YAML: ${CONFIG_YAML}
      SERVICE_ACCOUNT_JSON: ${SERVICE_ACCOUNT_JSON}
    restart: always
