version: "3.7"
services:
  notifier:
    container_name: pubsub-gateway
    image: pubsub-gateway
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      MODE: receiver
      CONFIG: ${CONFIG}
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
    restart: always
