version: 1
handlers:
  - subscription: remocon
    action:
      type: http
      method: POST
      header:
        "User-Agent":
          - "pubsub-gateway/v1"
      url: "http://localhost/api/v1"
      payload:
        remote: ${path "remote"}
        name: ${path "name"}
